---
- name: Install node and npm
  hosts: 34.210.235.139
  tasks:
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
        - nodejs
        - npm

- name: Create new user for node app
  hosts: 34.210.235.139
  vars_files:
    - project-vars
  tasks:
  - name: Create Linux user
    user:
      name: "{{user}}"
      group: admin

- name: Deploy Nodejs App
  hosts: 34.210.235.139
  vars_files:
    - project-vars
  become: True
  become_user: "{{user}}"
  tasks: 
  - name: Unpack the nodejs file
    unarchive: 
      src: "{{location}}/nodejs-app-{{version}}.tgz"
      dest: "{{destination}}"
  - name: Install dependencies
    npm: 
      path: "{{destination}}/package"
  - name: Start App
    command: 
      chdir: "{{destination}}/package/app/"
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    shell: ps aux | grep node
    register: app_status
  - debug: msg={{app_status}}  